include:
  - "config/**/*.rb"
  - "app/**/*.rb"
  - "lib/**/*.rake"
  - "script/**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
reporters:
  - rubocop
  - require_not_found
  - typecheck:normal